-- MySQL Script generated by MySQL Workbench
-- Tue Feb 25 23:12:16 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`direccion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`direccion` (
  `direccion_id` INT NOT NULL,
  `calle_col` VARCHAR(64) NOT NULL,
  `numero_col` VARCHAR(8) NOT NULL,
  `piso_col` VARCHAR(8) NOT NULL,
  `puerta_col` VARCHAR(8) NOT NULL,
  `ciudad_col` VARCHAR(64) NOT NULL,
  `codigo_postal_col` VARCHAR(12) NOT NULL,
  `pais_col` VARCHAR(64) NOT NULL,
  PRIMARY KEY (`direccion_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`proveedor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`proveedor` (
  `proveedor_id` INT NOT NULL AUTO_INCREMENT,
  `nombre_col` VARCHAR(32) NOT NULL,
  `direccion_col` INT NOT NULL,
  `telephone_col` VARCHAR(16) NOT NULL,
  `fax_col` VARCHAR(16) NOT NULL,
  `nif_col` VARCHAR(16) NOT NULL,
  PRIMARY KEY (`proveedor_id`),
  INDEX `direccion_id_fk_idx` (`direccion_col` ASC),
  CONSTRAINT `direccion_id_fk`
    FOREIGN KEY (`direccion_col`)
    REFERENCES `mydb`.`direccion` (`direccion_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`marca`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`marca` (
  `marca_id` INT NOT NULL,
  `nombre_col` VARCHAR(64) NOT NULL,
  `proveedor_id` INT NOT NULL,
  UNIQUE INDEX `marca_id_UNIQUE` (`marca_id` ASC),
  PRIMARY KEY (`marca_id`),
  UNIQUE INDEX `nombre_UNIQUE` (`nombre_col` ASC),
  INDEX `proveedor_id_idx` (`proveedor_id` ASC),
  CONSTRAINT `proveedor_id`
    FOREIGN KEY (`proveedor_id`)
    REFERENCES `mydb`.`proveedor` (`proveedor_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`color`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`color` (
  `color_id` INT NOT NULL,
  `nombre_col` VARCHAR(32) NOT NULL,
  PRIMARY KEY (`color_id`),
  UNIQUE INDEX `color_id_UNIQUE` (`color_id` ASC),
  UNIQUE INDEX `nombre_UNIQUE` (`nombre_col` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`montura`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`montura` (
  `montura_id` INT NOT NULL,
  `nombre_col` VARCHAR(16) NOT NULL,
  PRIMARY KEY (`montura_id`),
  UNIQUE INDEX `montura_id_UNIQUE` (`montura_id` ASC),
  UNIQUE INDEX `nombre_UNIQUE` (`nombre_col` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`gafa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`gafa` (
  `gafa_id` INT NOT NULL,
  `marca_id_col` INT NOT NULL,
  `graduacion_derecha_col` DOUBLE NOT NULL,
  `graduacion_izquierda_col` DOUBLE NOT NULL,
  `tipo_montura_id_col` INT NOT NULL,
  `color_id_montura_col` INT NOT NULL,
  `color_id_derecha_col` INT NOT NULL,
  `color_id_izquierda_col` INT NOT NULL,
  `precio_col` DOUBLE NOT NULL,
  `vendida_por_empleado_id_col` INT NOT NULL,
  PRIMARY KEY (`gafa_id`),
  INDEX `marca_id_idx` (`marca_id_col` ASC),
  INDEX `color_id_idx` (`color_id_montura_col` ASC, `color_id_derecha_col` ASC, `color_id_izquierda_col` ASC),
  INDEX `montura_id_idx` (`tipo_montura_id_col` ASC),
  CONSTRAINT `marca_id`
    FOREIGN KEY (`marca_id_col`)
    REFERENCES `mydb`.`marca` (`marca_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `color_id`
    FOREIGN KEY (`color_id_montura_col` , `color_id_derecha_col` , `color_id_izquierda_col`)
    REFERENCES `mydb`.`color` (`color_id` , `color_id` , `color_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `montura_id`
    FOREIGN KEY (`tipo_montura_id_col`)
    REFERENCES `mydb`.`montura` (`montura_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`cliente` (
  `cliente_id` INT NOT NULL,
  `nombre_col` VARCHAR(64) NOT NULL,
  `direccion_col` INT NOT NULL,
  `telefono_col` VARCHAR(16) NOT NULL,
  `email_col` VARCHAR(64) NOT NULL,
  `fecha_registro_col` BIGINT NOT NULL,
  `recomendado_por_cliente_col` INT NOT NULL,
  UNIQUE INDEX `cliente_id_UNIQUE` (`cliente_id` ASC),
  PRIMARY KEY (`cliente_id`),
  INDEX `recomendado_idx` (`recomendado_por_cliente_col` ASC),
  CONSTRAINT `recomendado`
    FOREIGN KEY (`recomendado_por_cliente_col`)
    REFERENCES `mydb`.`cliente` (`cliente_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
