-- MySQL Script generated by MySQL Workbench
-- Tue Feb 25 23:10:49 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`libro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`libro` (
  `libro_id` INT NOT NULL,
  `unidades_disponibles_col` INT NOT NULL,
  `precio_col` DOUBLE NOT NULL,
  PRIMARY KEY (`libro_id`),
  UNIQUE INDEX `libros_id_UNIQUE` (`libro_id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`usuario` (
  `usuario_id` INT NOT NULL,
  `email_col` VARCHAR(45) NOT NULL,
  `contraseñe_col` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`usuario_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`autor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`autor` (
  `autor_id` INT NOT NULL,
  `direccion_col` VARCHAR(45) NOT NULL,
  `numero_libros_escritos` INT NOT NULL,
  PRIMARY KEY (`autor_id`),
  UNIQUE INDEX `autor_id_UNIQUE` (`autor_id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`factura`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`factura` (
  `factura_id` INT NOT NULL,
  `usuario_usuario_id` INT NOT NULL,
  PRIMARY KEY (`factura_id`, `usuario_usuario_id`),
  INDEX `fk_factura_usuario1_idx` (`usuario_usuario_id` ASC),
  CONSTRAINT `fk_factura_usuario1`
    FOREIGN KEY (`usuario_usuario_id`)
    REFERENCES `mydb`.`usuario` (`usuario_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`libro_autor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`libro_autor` (
  `autor_autor_id` INT NOT NULL,
  `libro_libro_id` INT NOT NULL,
  PRIMARY KEY (`autor_autor_id`),
  INDEX `fk_libro_autor_autor1_idx` (`autor_autor_id` ASC),
  INDEX `fk_libro_autor_libro1_idx` (`libro_libro_id` ASC),
  CONSTRAINT `fk_libro_autor_autor1`
    FOREIGN KEY (`autor_autor_id`)
    REFERENCES `mydb`.`autor` (`autor_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_libro_autor_libro1`
    FOREIGN KEY (`libro_libro_id`)
    REFERENCES `mydb`.`libro` (`libro_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`factura_detalle`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`factura_detalle` (
  `factura_detalle_id` INT NOT NULL,
  `factura_factura_id` INT NOT NULL,
  `factura_usuario_usuario_id` INT NOT NULL,
  `libro_libro_id` INT NOT NULL,
  PRIMARY KEY (`factura_detalle_id`, `factura_factura_id`, `factura_usuario_usuario_id`),
  INDEX `fk_detalle_factura_factura1_idx` (`factura_factura_id` ASC, `factura_usuario_usuario_id` ASC),
  INDEX `fk_factura_detalle_libro1_idx` (`libro_libro_id` ASC),
  CONSTRAINT `fk_detalle_factura_factura1`
    FOREIGN KEY (`factura_factura_id` , `factura_usuario_usuario_id`)
    REFERENCES `mydb`.`factura` (`factura_id` , `usuario_usuario_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_factura_detalle_libro1`
    FOREIGN KEY (`libro_libro_id`)
    REFERENCES `mydb`.`libro` (`libro_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
