-- MySQL Script generated by MySQL Workbench
-- Tue Feb 25 19:22:25 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`cuadro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`cuadro` (
  `cuadro_id` INT NOT NULL AUTO_INCREMENT,
  `precio_col` DOUBLE NOT NULL,
  `autor_col` VARCHAR(45) NULL,
  PRIMARY KEY (`cuadro_id`),
  UNIQUE INDEX `cuadro_id_UNIQUE` (`cuadro_id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`comprador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`comprador` (
  `comprador_dni` VARCHAR(16) NOT NULL,
  `localidad_col` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`comprador_dni`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`cuadro_comprador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`cuadro_comprador` (
  `comprador_comprador_dni` VARCHAR(16) NOT NULL,
  `cuadro_cuadro_id` INT NOT NULL,
  PRIMARY KEY (`comprador_comprador_dni`),
  INDEX `fk_cuadro_comprador_comprador1_idx` (`comprador_comprador_dni` ASC),
  INDEX `fk_cuadro_comprador_cuadro1_idx` (`cuadro_cuadro_id` ASC),
  CONSTRAINT `fk_cuadro_comprador_comprador1`
    FOREIGN KEY (`comprador_comprador_dni`)
    REFERENCES `mydb`.`comprador` (`comprador_dni`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_cuadro_comprador_cuadro1`
    FOREIGN KEY (`cuadro_cuadro_id`)
    REFERENCES `mydb`.`cuadro` (`cuadro_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
