-- MySQL Script generated by MySQL Workbench
-- Tue Feb 25 23:10:17 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`usuario` (
  `usuario_id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(16) NOT NULL,
  `email_col` VARCHAR(45) NOT NULL,
  `contraseña_col` VARCHAR(32) NOT NULL,
  UNIQUE INDEX `nombre_UNIQUE` (`nombre` ASC),
  PRIMARY KEY (`usuario_id`, `nombre`),
  UNIQUE INDEX `usuario_id_UNIQUE` (`usuario_id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`video`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`video` (
  `video_id` INT NOT NULL,
  `descripción_col` TEXT NOT NULL,
  `titulo_col` VARCHAR(64) NOT NULL,
  `url_col` VARCHAR(96) NOT NULL,
  `name_col` VARCHAR(48) NOT NULL,
  PRIMARY KEY (`video_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`usuario_tiene_video`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`usuario_tiene_video` (
  `usuario_usuario_id` INT NOT NULL,
  `video_video_id` INT NOT NULL,
  PRIMARY KEY (`usuario_usuario_id`, `video_video_id`),
  INDEX `fk_usuario_tiene_video_video1_idx` (`video_video_id` ASC),
  INDEX `fk_usuario_tiene_video_usuario1_idx` (`usuario_usuario_id` ASC),
  CONSTRAINT `fk_usuario_tiene_video_video1`
    FOREIGN KEY (`video_video_id`)
    REFERENCES `mydb`.`video` (`video_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_usuario_tiene_video_usuario1`
    FOREIGN KEY (`usuario_usuario_id`)
    REFERENCES `mydb`.`usuario` (`usuario_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
