-- MySQL Script generated by MySQL Workbench
-- Tue Feb 25 23:11:33 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`usuario` (
  `usuario_id` INT NOT NULL,
  `nombre_col` VARCHAR(45) NOT NULL,
  `email_col` VARCHAR(45) NOT NULL,
  `contraseña_col` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`usuario_id`),
  UNIQUE INDEX `usuario_id_UNIQUE` (`usuario_id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`foto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`foto` (
  `foto_id` INT NOT NULL,
  `lugar_col` VARCHAR(45) NOT NULL,
  `url_col` VARCHAR(95) NOT NULL,
  PRIMARY KEY (`foto_id`),
  UNIQUE INDEX `url_col_UNIQUE` (`url_col` ASC),
  UNIQUE INDEX `foto_id_UNIQUE` (`foto_id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`usuario_tiene_foto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`usuario_tiene_foto` (
  `usuario_usuario_id` INT NOT NULL,
  `foto_foto_id` INT NOT NULL,
  PRIMARY KEY (`usuario_usuario_id`, `foto_foto_id`),
  INDEX `fk_usuario_tiene_foto_usuario_idx` (`usuario_usuario_id` ASC),
  INDEX `fk_usuario_tiene_foto_foto1_idx` (`foto_foto_id` ASC),
  CONSTRAINT `fk_usuario_tiene_foto_usuario`
    FOREIGN KEY (`usuario_usuario_id`)
    REFERENCES `mydb`.`usuario` (`usuario_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_usuario_tiene_foto_foto1`
    FOREIGN KEY (`foto_foto_id`)
    REFERENCES `mydb`.`foto` (`foto_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`manera_contacto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`manera_contacto` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(128) NOT NULL,
  UNIQUE INDEX `id_UNIQUE` (),
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`amistad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`amistad` (
  `usuario_id1` INT NOT NULL,
  `usuario_id2` INT NOT NULL,
  `manera_contacto_id` INT NOT NULL,
  INDEX `usuario_id1_idx` (`usuario_id1` ASC, `usuario_id2` ASC),
  INDEX `manera_contacto_id_fk_idx` (`manera_contacto_id` ASC),
  CONSTRAINT `usuario_id_fk`
    FOREIGN KEY (`usuario_id1` , `usuario_id2`)
    REFERENCES `mydb`.`usuario` (`usuario_id` , `usuario_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `manera_contacto_id_fk`
    FOREIGN KEY (`manera_contacto_id`)
    REFERENCES `mydb`.`manera_contacto` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
